name: Test File Upload

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest 
    strategy:
      matrix: 
        builds: [foo, bar, baz]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create test file
        run: |
          echo "This is a test file ${{ matrix.builds }}." > ${{ matrix.builds }}.txt

      - uses: actions/upload-artifact@v4 # upload the results
        with: 
          name: ${{ matrix.builds }}-firmware.zip
          path: ./*.txt

  link:
    needs: build # make sure the artifacts are uploaded first
    runs-on: ubuntu-latest 

    permissions:
        contents: write # for commenting on your commit
        pull-requests: write # for commenting on your pr
    steps:
      - uses: beni69/artifact-link@v1
        with:
          token: ${{ github.token }}